### ISSUE TITLE
combining the speaker into one entry, untile the speaker changes

### ISSUE THREAD

**Issue by laarisyko** [Majdoddin/nlp#2]
I really like your work. For the sake of readability it would be great if the text appears in blocks until the speaker changes. The link to each individual timestamp could be hidden under the actual text. In principle the same thing as otter.ai does. 

It could look like this:

![grafik](https://user-images.githubusercontent.com/30383523/197778964-f30816e8-03e1-42ff-b124-25295139aacc.png)

`<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Lexicap</title>
    <style>
        body {
            font-family: sans-serif;
            font-size: 22px;
			color: white;
			background: #1e1f45;
            padding: 0 0 1em 0;
			
        }
		a {
			color: black;
		}
		a:link { 
			color: white;
			text-decoration: none; 
		}
		a:visited {
			text-decoration: none;
		}
		a:hover {
			color: white;
			background-color: #e8347d;
			text-decoration: none;
		}
		a:active {
			text-decoration: none; 
			}
        .l {
          color: #050;
        }
        .s {
            display: inline-block;
        }
        .e {
            display: inline-block;
        }
        .t {
            display: inline-block;
        }
		.text_block {
			width: 60%;
		}
		.name_1 {
			font-size: 23px;
			color: #fa4236;
			font-weight: bold;
		}
		.name_2 {
			font-size: 23px;
			color: #feea00;
			font-weight: bold;
		}
        #player {
		position: sticky;
		top: 20px;
		float: right;
	}
    </style>
  </head>
  <body>
    <h2>Yann LeCun: Dark Matter of Intelligence and Self-Supervised Learning | Lex Fridman Podcast #258</h2>
  <div  id="player"></div>
    <script>
      var tag = document.createElement('script');
      tag.src = "https://www.youtube.com/iframe_api";
      var firstScriptTag = document.getElementsByTagName('script')[0];
      firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);
      var player;
      function onYouTubeIframeAPIReady() {
        player = new YT.Player('player', {
          height: '210',
          width: '340',
          videoId: 'SGzMElJ11Cc',
        });
      }
      function setCurrentTime(timepoint) {
        player.seekTo(timepoint);
   player.playVideo();
   }
    </script><br>
			<div class=text_block>
				<span class=name_1>Lex</span>  
				<br>
				<a href="javascript:void(0);" onclick=setCurrentTime(0)>The following is a conversation with Yann LeCun</a>
				<a href="javascript:void(0);" onclick=setCurrentTime(2)>his second time on the podcast.</a>
				<a href="javascript:void(0);" onclick=setCurrentTime(4)>He is the chief AI scientist at Meta, formerly Facebook,</a>
				<a href="javascript:void(0);" onclick=setCurrentTime(9)>professor at NYU, touring award winner,</a>
				<a href="javascript:void(0);" onclick=setCurrentTime(13)>one of the seminal figures in the history</a>
				<a href="javascript:void(0);" onclick=setCurrentTime(15)>of machine learning and artificial intelligence,</a>
				<a href="javascript:void(0);" onclick=setCurrentTime(18)>and someone who is brilliant and opinionated</a>
				<a href="javascript:void(0);" onclick=setCurrentTime(21)>in the best kind of way,</a>
				<a href="javascript:void(0);" onclick=setCurrentTime(23)>and so is always fun to talk to.</a>
				<br>
				<br>
			</div>
			<div class=text_block>
				<span class=name_2>Yann</span> 
				<br>
				<a href="javascript:void(0);" onclick=setCurrentTime(49)>I'll start by the dark matter part.</a>
				<a href="javascript:void(0);" onclick=setCurrentTime(51)>There is obviously a kind of learning</a>
				<a href="javascript:void(0);" onclick=setCurrentTime(55)>that humans and animals are doing</a>
				<a href="javascript:void(0);" onclick=setCurrentTime(59)>that we currently are not reproducing properly</a>
				<br>
				<br>
			</div>

			
			`

**Comment by Majdoddin** [comment]
As you wish :) Thank you for your nice suggestion. Check the updated [Colab notebook](https://colab.research.google.com/drive/12W6bR-C6NIEjAML19JubtzHPIlVxdaUq?usp=sharing) and the [result](https://majdoddin.github.io/dyson.html#00:02:18.85). 
And, please consider supporting my work with a [donation](https://www.paypal.com/donate/?hosted_button_id=KMGB76UZS5SH8).

**Comment by laarisyko** [comment]
I made a small donation ;) 
Would you consider to reply in this thread: https://github.com/Stage-Whisper/Stage-Whisper/discussions/101
I belief you are a very good fit for the project :)

**Comment by Majdoddin** [comment]
I was delighted :) Thank you very much. 
I am heading there ...
